[window]
opacity = 1
blur = false
decorations = "Transparent"
startup_mode = "Fullscreen"
decorations_theme_variant = "Dark"

[window.padding]
x = 0
y = 0

[font]
size = 12

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[cursor]
thickness = 0.1

[cursor.style]
shape = "Beam"
blinking = "Never"

[colors.primary]
background = "#000000"

[[keyboard.bindings]]
key = "F"
mods = "Control|Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "C"
mods = "Control|Alt"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Alt"
action = "Paste"

[terminal]
shell = { program = "/bin/fish"}

[general]
import = ["~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"]
