[window]
opacity = 0.6
blur = true
decorations = "None"

[window.padding]
x = 0
y = 0

[font]
size = 14.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[cursor]
thickness = 0.15

[cursor.style]
shape = "Beam"
blinking = "Never"

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[[keyboard.bindings]]
key = "F"
mods = "Control|Alt"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "C"
mods = "Control|Alt"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Alt"
action = "Paste"
