[colors.primary]
background = '#11131a'
foreground = '#e1e2ec'

[colors.selection]
text = '#e1e2ec'
background = '#314f0f'

[colors.cursor]
text = '#11131a'
cursor = '#aed283'

[colors.normal]
black   = '#11131a'
red     = '#f1836c'
green   = '#70d269'
yellow  = '#ffec72'
blue    = '#9ec76d'
magenta = '#42611e'
cyan    = '#aed283'
white   = '#d6dccf'

[colors.bright]
black   = '#83887e'
red     = '#ffb09f'
green   = '#aafba3'
yellow  = '#fff2a5'
blue    = '#c5e79d'
magenta = '#e0ffbb'
cyan    = '#ebffd3'
white   = '#fcfff8'
