[colors.primary]
background = '#121318'
foreground = '#e3e1e9'

[colors.selection]
text = '#e3e1e9'
background = '#384379'

[colors.cursor]
text = '#121318'
cursor = '#b9c3ff'

[colors.normal]
black   = '#121318'
red     = '#e44e44'
green   = '#6ed66f'
yellow  = '#dbd47b'
blue    = '#6e79de'
magenta = '#959bbf'
cyan    = '#b9c3ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0635f'
green   = '#86e086'
yellow  = '#e8e297'
blue    = '#c6d1ff'
magenta = '#5d78b9'
cyan    = '#7371bb'
white   = '#ffffff'
