[colors.primary]
background = '#1d100b'
foreground = '#f9ddd3'

[colors.selection]
text = '#f9ddd3'
background = '#7e2c00'

[colors.cursor]
text = '#1d100b'
cursor = '#ffb598'

[colors.normal]
black   = '#1d100b'
red     = '#e14982'
green   = '#99d66e'
yellow  = '#dbab7b'
blue    = '#bd6c4c'
magenta = '#bf9281'
cyan    = '#ffb598'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f92'
green   = '#abe086'
yellow  = '#e8c097'
blue    = '#ffc2a3'
magenta = '#b76055'
cyan    = '#9b7052'
white   = '#ffffff'
