cursor #e1e2ec
cursor_text_color #c2c6d6

foreground            #e1e2ec
background            #11131a
selection_foreground  #45263c
selection_background  #e8b9d5
url_color             #aed283

color0   #11131a
color1   #f1836c
color2   #70d269
color3   #ffec72
color4   #9ec76d
color5   #42611e
color6   #aed283
color7   #d6dccf
color8   #83887e
color9   #ffb09f
color10  #aafba3
color11  #fff2a5
color12  #c5e79d
color13  #e0ffbb
color14  #ebffd3
color15  #fcfff8
