cursor #e2e1ef
cursor_text_color #c6c5d3

foreground            #e2e1ef
background            #11131c
selection_foreground  #312c4c
selection_background  #c9c1ea
url_color             #bac3ff

color0   #11131c
color1   #ff7296
color2   #7fff95
color3   #ffd772
color4   #a3adf2
color5   #3b4376
color6   #bac3ff
color7   #eff1ff
color8   #999ba5
color9   #ff9fb7
color10  #a5ffb4
color11  #ffe6a5
color12  #c4ccff
color13  #ced5ff
color14  #dfe3ff
color15  #f8f9ff
