cursor #e4e1ec
cursor_text_color #c7c4d6

foreground            #e4e1ec
background            #13131a
selection_foreground  #4a2531
selection_background  #f0b8c6
url_color             #95d69b

color0   #13131a
color1   #f6906e
color2   #6bd66b
color3   #ffef72
color4   #81cb88
color5   #2b6330
color6   #95d69b
color7   #d3e0d4
color8   #808b81
color9   #ffb79f
color10  #a6ffa5
color11  #fff5a5
color12  #aeebb4
color13  #c8ffcd
color14  #dcffdf
color15  #f8fff9
