[ui.constraints]
max_height = 3
max_width = 50

[[stations]]
id = "echo"

[stations.metadata]

[stations.behavior]
picker_type = "EntryBox"

[[stations.behavior.key_maps]]
modifiers = ""
key = "Enter"
replace_string = "{}"

[stations.behavior.key_maps.action]
ExecuteWithTyped = [
    "echo",
    "{}",
]

[[stations]]
id = "git-add"

[stations.metadata]

[stations.behavior]
search_type = "FuzzySearch"

[stations.behavior.picker_type.SingleChoice]
command = [
    "git",
    "diff",
    "--name-only",
]
separator = """

"""

[[stations.behavior.key_maps]]
modifiers = ""
key = "Enter"
replace_string = "{}"

[stations.behavior.key_maps.action]
ExecuteForEachAndExit = [
    "git",
    "add",
    "{}",
]
