-- Auto-generated by DMS — do not edit manually.
-- Remove require("dms.cursor") from hyprland.lua to override.
--
-- Seeded from niri/dms/cursor.kdl (Adwaita, size 27, hide-after-inactive-ms 5000).

hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "27")
hl.env("HYPRCURSOR_THEME", "Adwaita")
hl.env("HYPRCURSOR_SIZE", "27")

hl.config({
	cursor = {
		inactive_timeout = 5,
	},
})
