-- Auto-generated by DMS — do not edit manually.
-- Remove require("dms.layout") from hyprland.lua to override.
--
-- Seeded from niri/dms/layout.kdl (gaps 4, border width 2) and
-- DankMaterialShell/settings.json (cornerRadius: 18). DMS rewrites this file.

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 4,
		border_size = 2,
	},
	decoration = {
		rounding = 18,
	},
})
