-- Auto-generated by DMS — do not edit manually.
-- Remove require("dms.outputs") from hyprland.lua to override.
--
-- Outputs are DMS-managed (as they are on niri, where config.kdl never includes
-- output.kdl and only dms/outputs.kdl applies). DMS's output-profile manager
-- rewrites this file and applies profiles live over wlr-output-management.

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
