-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/
--
-- Port of ~/.config/niri. The two setups are meant to differ in exactly one way:
-- niri scrolls, Hyprland tiles (dwindle). Keymap, DankMaterialShell integration,
-- colours and blur are kept the same.
--
-- File layout mirrors niri/:
--   hyprland.lua  <-  niri/config.kdl
--   binds.lua     <-  niri/binds.kdl + niri/dms/binds.kdl
--   looks.lua     <-  niri/looks.kdl
--   dms/*.lua     <-  niri/dms/*.kdl   (auto-generated by DMS)

-- Requires a DMS-managed fragment. Missing files are not fatal: DMS writes them
-- lazily (colors on theme change, outputs on profile change), and a half-deployed
-- DMS must never cost us a session. Failures are swallowed rather than logged --
-- anything we could call to report them is itself unavailable if the config is
-- this broken.
local function require_dms(mod)
  pcall(require, mod)
end

-------------------
---- AUTOSTART ----
-------------------

-- Starting hyprland-session.target activates graphical-session.target, which is
-- what pulls in dms.service. See setup.sh.
hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("systemctl --user start hyprland-session.target")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("TERMINAL", "kitty")

---------------
---- INPUT ----
---------------

-- niri/config.kdl: input { focus-follows-mouse; keyboard { repeat-delay 300;
-- repeat-rate 85; xkb { options "ctrl:nocaps" } numlock } touchpad { tap; natural-scroll } }
hl.config({
  input = {
    -- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
    kb_layout          = "",
    kb_options         = "ctrl:nocaps",
    numlock_by_default = true,

    repeat_delay       = 300,
    repeat_rate        = 85,

    follow_mouse       = 1, -- niri: focus-follows-mouse

    touchpad           = {
      tap_to_click   = true,
      natural_scroll = true,
    },
  },
})

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Gaps, border width and corner rounding are deliberately NOT set here: they come
-- from dms/layout.lua, exactly as niri/dms/layout.kdl overrides config.kdl's `gaps 8`.
hl.config({
  general = {
    layout = "dwindle",
  },

  dwindle = {
    preserve_split = true,
  },

  binds = {
    -- niri folds "or-monitor-left/right" into its focus/move actions; this is
    -- how Hyprland gets the same edge-crossing behaviour on Mod+H/L etc.
    window_direction_monitor_fallback = true,
  },

  misc = {
    disable_hyprland_logo    = true,
    disable_splash_rendering = true,
    force_default_wallpaper  = 0,
  },

  animations = {
    enabled = true,
  },
})

-- niri/config.kdl: animations { slowdown 1.5 }
-- Hyprland has no global slowdown, and `speed` here is a duration in deciseconds
-- (higher = slower), so these are DMS's Hyprland defaults multiplied by 1.5.
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.5, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4.5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 6.0, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 7.5, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 4.5, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 4.5, bezier = "default" })

------------------
---- INCLUDES ----
------------------

-- Order matters: later wins. looks.lua sits after dms.windowrules so the blur
-- rules are applied last.
require_dms("dms.colors")
require_dms("dms.outputs")
require_dms("dms.layout")
require_dms("dms.cursor")
require_dms("dms.windowrules")

require("looks")
require("binds")
