[colors]
background = '#11131a'
foreground = '#e1e2ec'

cursor_bg = '#aed283'
cursor_fg = '#11131a'
cursor_border = '#aed283'

selection_bg = '#314f0f'
selection_fg = '#e1e2ec'

ansi = ['#11131a', '#f1836c', '#70d269', '#ffec72', '#9ec76d', '#314f0f', '#aed283', '#d6dccf']
brights = ['#3f433b', '#ffb09f', '#aafba3', '#fff2a5', '#c5e79d', '#e0ffbb', '#ebffd3', '#fcfff8']
